CREATE OR REPLACE DATABASE EXCEPTION_RESOLVER;
CREATE OR REPLACE SCHEMA EXCEPTION_RESOLVER.ENTERPRISE;

USE DATABASE EXCEPTION_RESOLVER;
USE SCHEMA ENTERPRISE;

CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID VARCHAR PRIMARY KEY,
    SUPPLIER_NAME VARCHAR,
    CATEGORY VARCHAR,
    COUNTRY VARCHAR,
    RISK_LEVEL VARCHAR,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE CONTRACTS (
    CONTRACT_ID VARCHAR PRIMARY KEY,
    SUPPLIER_ID VARCHAR,
    CONTRACT_START DATE,
    CONTRACT_END DATE,
    CURRENCY VARCHAR,
    PAYMENT_TERMS VARCHAR,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE CONTRACT_AMENDMENTS (
    AMENDMENT_ID VARCHAR PRIMARY KEY,
    CONTRACT_ID VARCHAR,
    AMENDMENT_DATE TIMESTAMP,
    FIELD_CHANGED VARCHAR,
    OLD_VALUE VARCHAR,
    NEW_VALUE VARCHAR,
    REASON VARCHAR
);

CREATE OR REPLACE TABLE PURCHASE_ORDERS (
    PO_ID VARCHAR PRIMARY KEY,
    SUPPLIER_ID VARCHAR,
    CONTRACT_ID VARCHAR,
    PO_DATE DATE,
    CURRENCY VARCHAR,
    TOTAL_AMOUNT NUMBER(18,2),
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE INVOICES (
    INVOICE_ID VARCHAR PRIMARY KEY,
    PO_ID VARCHAR,
    SUPPLIER_ID VARCHAR,
    INVOICE_DATE DATE,
    CURRENCY VARCHAR,
    TOTAL_AMOUNT NUMBER(18,2),
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR PRIMARY KEY,
    PO_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_DATE DATE,
    ORDER_AMOUNT NUMBER(18,2),
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE SHIPMENTS (
    SHIPMENT_ID VARCHAR PRIMARY KEY,
    ORDER_ID VARCHAR,
    SUPPLIER_ID VARCHAR,
    PROMISED_DATE DATE,
    ACTUAL_DATE DATE,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE SUPPLIER_COMMUNICATIONS (
    COMMUNICATION_ID VARCHAR PRIMARY KEY,
    SUPPLIER_ID VARCHAR,
    COMMUNICATION_DATE TIMESTAMP,
    CHANNEL VARCHAR,
    SUBJECT VARCHAR,
    CONTENT VARCHAR
);

CREATE OR REPLACE TABLE ERP_EVENTS (
    EVENT_ID VARCHAR PRIMARY KEY,
    EVENT_TIMESTAMP TIMESTAMP,
    ENTITY_TYPE VARCHAR,
    ENTITY_ID VARCHAR,
    EVENT_TYPE VARCHAR,
    DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE POLICIES (
    POLICY_ID VARCHAR PRIMARY KEY,
    POLICY_NAME VARCHAR,
    POLICY_TEXT VARCHAR,
    VERSION VARCHAR,
    EFFECTIVE_DATE DATE
);

CREATE OR REPLACE TABLE EXCEPTIONS (
    EXCEPTION_ID VARCHAR PRIMARY KEY,
    DETECTED_AT TIMESTAMP,
    EXCEPTION_TYPE VARCHAR,
    ENTITY_TYPE VARCHAR,
    ENTITY_ID VARCHAR,
    SEVERITY VARCHAR,
    STATUS VARCHAR,
    DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE EXCEPTION_AUDIT_LOG (
    AUDIT_ID VARCHAR PRIMARY KEY,
    EXCEPTION_ID VARCHAR,
    TIMESTAMP TIMESTAMP,
    STAGE VARCHAR,
    AGENT VARCHAR,
    ACTION VARCHAR,
    DECISION VARCHAR,
    REASON VARCHAR,
    EVIDENCE VARCHAR
);